/**
 * Runtime Message Passing Types
 *
 * Typed message contracts for chrome.runtime.sendMessage()
 * and chrome.tabs.sendMessage(). These prevent the #1 source
 * of bugs in multi-context extensions: mismatched message shapes
 * between popup ↔ content script ↔ service worker.
 */

import type { Conversation } from "./chat";
import type { ExtractionResult, ValidationResult, DiagnosticData } from "./extraction";

// Content Script Messages

/** Popup → Content Script: request chat extraction. */
export interface ExtractChatMessage {
  type: "EXTRACT_CHAT";
}

/** Content Script → Popup: extraction succeeded. */
export interface ExtractChatSuccess {
  type: "EXTRACT_CHAT_RESULT";
  ok: true;
  payload: ExtractionResult;
}

/** Content Script → Popup: extraction failed (all layers or validation). */
export interface ExtractChatError {
  type: "EXTRACT_CHAT_RESULT";
  ok: false;
  error: string;
  /** Present when failure was a validation error (not a DOM failure). */
  validationErrors?: ValidationResult["errors"];
  /**
   * Diagnostic data collected at the time of failure.
   * Present when all extraction layers fail (not validation failures).
   */
  diagnostics?: DiagnosticData;
  /**
   * Privacy-safe DOM skeleton generated by the skeletonizer.
   * Contains only structural info (tags, classes, data-* keys) — no user text.
   * Present when all extraction layers fail.
   */
  skeleton?: string;
  /**
   * Set to true when extraction failed because the user is not viewing a
   * conversation (e.g. they are on the ChatGPT/Gemini home/new-chat page).
   * When true, the popup shows a friendly "open a chat" prompt instead of
   * the bug-report UI.
   */
  emptyPage?: boolean;
}

export type ExtractChatResponse = ExtractChatSuccess | ExtractChatError;

/** Popup → Content Script: check if content script is alive. */
export interface PingMessage {
  type: "PING";
}

/** Content Script → Popup: alive confirmation. */
export interface PingResponse {
  type: "PONG";
}

// Service Worker Messages

/** Popup → Service Worker: send conversation for Markdown export. */
export interface ExportMarkdownMessage {
  type: "EXPORT_MARKDOWN";
  payload: Conversation;
}

/** Service Worker → Popup: export succeeded. */
export interface ExportMarkdownSuccess {
  type: "EXPORT_MARKDOWN_RESULT";
  ok: true;
  filename: string;
}

/** Service Worker → Popup: export failed. */
export interface ExportMarkdownError {
  type: "EXPORT_MARKDOWN_RESULT";
  ok: false;
  error: string;
}

export type ExportMarkdownResponse = ExportMarkdownSuccess | ExportMarkdownError;

/** Popup → Service Worker: send conversation for PDF summary. */
export interface ExportPdfMessage {
  type: "EXPORT_PDF";
  payload: Conversation;
}

/** Service Worker → Popup: PDF export completed (file downloaded). */
export interface ExportPdfSuccess {
  type: "EXPORT_PDF_RESULT";
  ok: true;
  filename: string;
}

/** Service Worker → Popup: PDF export failed. */
export interface ExportPdfError {
  type: "EXPORT_PDF_RESULT";
  ok: false;
  error: string;
}

export type ExportPdfResponse = ExportPdfSuccess | ExportPdfError;

/** Popup → Service Worker: probe the Gemini API with a minimal request. */
export interface TestConnectionMessage {
  type: "TEST_CONNECTION";
  /** Model to test against (reads from preferences if omitted). */
  model?: string;
}

/** Service Worker → Popup: connection probe succeeded. */
export interface TestConnectionSuccess {
  type: "TEST_CONNECTION_RESULT";
  ok: true;
  /** Model that was probed (e.g. "gemini-1.5-flash"). */
  model: string;
}

/** Service Worker → Popup: connection probe failed. */
export interface TestConnectionError {
  type: "TEST_CONNECTION_RESULT";
  ok: false;
  error: string;
}

export type TestConnectionResponse = TestConnectionSuccess | TestConnectionError;

// Background Export Status (Popup <-> Service Worker)

export interface GetExportStatusMessage {
  type: "GET_EXPORT_STATUS";
  url: string;
}

export interface ExportStatusResponse {
  active: boolean;
  mode?: "md" | "pdf";
}

export interface ExportStatusUpdateMessage {
  type: "EXPORT_STATUS_UPDATE";
  url: string;
  status: "success" | "fail";
  mode: "md" | "pdf";
  filename?: string;
  error?: string;
}

// Offscreen Messages (Service Worker <-> Offscreen Document)

/** Service Worker → Offscreen: render markdown as PDF and download it. */
export interface GeneratePdfMessage {
  type: "GENERATE_PDF";
  markdown: string;
  filename: string;
}

/** Offscreen → Service Worker: PDF generated successfully. */
export interface OffscreenPdfSuccess {
  type: "OFFSCREEN_PDF_RESULT";
  ok: true;
  filename: string;
  dataUrl: string;
}

/** Offscreen → Service Worker: PDF generation failed. */
export interface OffscreenPdfError {
  type: "OFFSCREEN_PDF_RESULT";
  ok: false;
  error: string;
}

export type OffscreenPdfResponse = OffscreenPdfSuccess | OffscreenPdfError;

/** All possible outgoing messages (popup → content script / service worker). */
export type RuntimeMessage =
  | ExtractChatMessage
  | PingMessage
  | ExportMarkdownMessage
  | ExportPdfMessage
  | TestConnectionMessage
  | GetExportStatusMessage
  | ExportStatusUpdateMessage
  | GeneratePdfMessage;
